@extends('layouts.app')

@section('content')

<section id="white" class="padding">
	<div class="container">
		<div class="row ">
		<div class="title text-center"><h2>{{$title}}</h2></div>
			<div id="accordion">
			  <div class="card">
				<div class="card-header" id="headingOne">
				  <h5 class="mb-0">
					<button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					  What is the price of a ticket?
					</button>
				  </h5>
				</div>

				<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
				  <div class="card-body">
					The price of a ticket varies between raffles and is set by the host. The minimum possible price of a ticket is £1 while the maximum is £10.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingTwo">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
					  How can I buy tickets?
					</button>
				  </h5>
				</div>
				<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
				  <div class="card-body">
					You can buy tickets by visiting the raffle page for the prize you want to win, selecting the number of tickets you would like to purchase and by answering a multiple choice question.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingThree">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
					  Why do you charge transaction fees?
					</button>
				  </h5>
				</div>
				<div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
				  <div class="card-body">
					We charge transaction fees to cover the transaction costs we incur through PayPal.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingfour">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapsefour" aria-expanded="false" aria-controls="collapsefour">
					  What are my chances of winning?
					</button>
				  </h5>
				</div>
				<div id="collapsefour" class="collapse" aria-labelledby="headingfour" data-parent="#accordion">
				  <div class="card-body">
					The odds of winning a prize depend on the total number of tickets issued and the number of tickets you purchase. For example, if 100 tickets have been issued and you purchase 2 tickets, the odds of you winning start from 1/50. However, if in the same example 50% of the entrants answered the question incorrectly, then the odds of you winning would increase to 1/25.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingfive">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapsefive" aria-expanded="false" aria-controls="collapsefive">
					 What does it mean when a host has a green tick next to their name?
					</button>
				  </h5>
				</div>
				<div id="collapsefive" class="collapse" aria-labelledby="headingfive" data-parent="#accordion">
				  <div class="card-body">
					The green tick means the company hosting the raffle has been verified by Rafflrs.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingsix">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapsesix" aria-expanded="false" aria-controls="collapsesix">
					  What happens if the reserve ticket quantity is not met?
					</button>
				  </h5>
				</div>
				<div id="collapsesix" class="collapse" aria-labelledby="headingsix" data-parent="#accordion">
				  <div class="card-body">
					When you create a raffle you can specify a reserve ticket quantity – if the number of tickets sold do not reach this reserve quantity, the prize will not be raffled away. Instead, the raffle will be cashed out, which means the winner will receive the ticket revenues generated by the raffle (minus 10% commission).
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingseven">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseseven" aria-expanded="false" aria-controls="collapseseven">
					  How can I tell if a raffle has been cashed out?
					</button>
				  </h5>
				</div>
				<div id="collapseseven" class="collapse" aria-labelledby="headingseven" data-parent="#accordion">
				  <div class="card-body">
					A stamp of a green pound sign indicates a cashed out raffle. The recent winners page for a cashed out raffle will have this stamp on the product image along with the prize money received by the winner.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingeight">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseeight" aria-expanded="false" aria-controls="collapseeight">
					  How is the winner chosen?
					</button>
				  </h5>
				</div>
				<div id="collapseeight" class="collapse" aria-labelledby="headingeight" data-parent="#accordion">
				  <div class="card-body">
					The winning ticket is selected automatically at random from amongst all purchased tickets associated with entrants who answered the multiple choice question for that specific raffle correctly.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingnine">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapsenine" aria-expanded="false" aria-controls="collapsenine">
					  When will the winner be chosen?
					</button>
				  </h5>
				</div>
				<div id="collapsenine" class="collapse" aria-labelledby="headingnine" data-parent="#accordion">
				  <div class="card-body">
					The winner will be chosen as soon as the raffle has ended.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="headingten">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseten" aria-expanded="false" aria-controls="collapseten">
					  How are hosts and winners notified?
					</button>
				  </h5>
				</div>
				<div id="collapseten" class="collapse" aria-labelledby="headingten" data-parent="#accordion">
				  <div class="card-body">
					Hosts and winners are notified via email and can also be seen on our recent winners page. Winners can also view their winning ticket under ‘My Raffles’ on their dashboard.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading11">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse11" aria-expanded="false" aria-controls="collapse11">
					 What happens if I win a raffle?
					</button>
				  </h5>
				</div>
				<div id="collapse11" class="collapse" aria-labelledby="heading11" data-parent="#accordion">
				  <div class="card-body">
					You will receive an automatic email which will notify you of your win and include contact details of the raffle host, allowing you to contact them to organise delivery or collection of the prize.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading12">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse12" aria-expanded="false" aria-controls="collapse12">
					  What if I do not receive the prize or it is not as advertised?
					</button>
				  </h5>
				</div>
				<div id="collapse12" class="collapse" aria-labelledby="heading12" data-parent="#accordion">
				  <div class="card-body">
					If you do not receive the prize or it is not as advertised, please get in touch with us at contact@rafflrs.com. If the issue is not resolved the raffle will be cashed out and you will receive the ticket revenues generated by the raffle (minus 10% commission).
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading13">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse13" aria-expanded="false" aria-controls="collapse13">
						How do I create a raffle?
					</button>
				  </h5>
				</div>
				<div id="collapse13" class="collapse" aria-labelledby="heading13" data-parent="#accordion">
				  <div class="card-body">
					You can create a raffle by signing up and pressing the ‘Create a Raffle’ button at the top right of the site. This will redirect you to the Create a Raffle form on the dashboard where you can easily create a raffle. The raffle will go live once it has been approved.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading14">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse14" aria-expanded="false" aria-controls="collapse14">
					  What happens when a raffle I’m hosting ends?
					</button>
				  </h5>
				</div>
				<div id="collapse14" class="collapse" aria-labelledby="heading14" data-parent="#accordion">
				  <div class="card-body">
					You will receive an automatic email which will notify you that your raffle has ended and a winner has been chosen. The email will include contact details for the winner of your raffle, allowing you to contact them to organise delivery or collection of the prize.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading15">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse15" aria-expanded="false" aria-controls="collapse15">
					  How will I receive the ticket revenues generated once my raffle has successfully ended?
					</button>
				  </h5>
				</div>
				<div id="collapse15" class="collapse" aria-labelledby="heading15" data-parent="#accordion">
				  <div class="card-body">
					Ticket revenues are transferred via PayPal – you will need to add your PayPal email in the ‘My Account’ section on your dashboard. We will send the funds once the winner has verified that they have received the prize.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading16">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse16" aria-expanded="false" aria-controls="collapse16">
					 How will I receive money from a cashed out raffle?
					</button>
				  </h5>
				</div>
				<div id="collapse16" class="collapse" aria-labelledby="heading16" data-parent="#accordion">
				  <div class="card-body">
					Ticket revenues are transferred via PayPal – you will need to add your PayPal email in the ‘My Account’ section on your dashboard.
				  </div>
				</div>
			  </div>
			  <div class="card">
				<div class="card-header" id="heading17">
				  <h5 class="mb-0">
					<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse17" aria-expanded="false" aria-controls="collapse17">
					 How much commission do you charge?
					</button>
				  </h5>
				</div>
				<div id="collapse17" class="collapse" aria-labelledby="heading17" data-parent="#accordion">
				  <div class="card-body">
					We charge a 10% commission on revenue generated from ticket sales.
				  </div>
				</div>
			  </div>
			</div>
		</div>
	</div>
</section>

@endsection